version: '3.8'

services:
  vjepa2-classifier:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: vjepa2-local
    ports:
      - "8080:8080"
    environment:
      - USE_GCS=false
      - ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests  # Mount test directory for video files
      - model_cache:/root/.cache  # Cache model downloads
      - /tmp:/tmp  # Share temp directory with host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G
    restart: unless-stopped

  # Optional: nginx proxy for production-like testing
  nginx:
    image: nginx:alpine
    container_name: vjepa2-nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vjepa2-classifier
    profiles:
      - production-test
    restart: unless-stopped

volumes:
  model_cache:
    driver: local

networks:
  default:
    name: vjepa2-network