# Webcam Monitor Configuration

service:
  # Service mode: "local" or "cloud"
  mode: "cloud"
  # Local service URL (used when mode: "local")
  local_url: "http://localhost:8080"
  # Cloud Run service URL (used when mode: "cloud")
  cloud_url: "https://vjepa2-classifier-267313437201.us-central1.run.app"
  endpoint: "/classify-upload"
  timeout: 30

camera:
  # Camera index - will auto-detect Logitech Brio
  # Set to specific index if auto-detection fails
  # Currently detected: 0=C270 HD WEBCAM (Logitech), 1=FaceTime HD Camera
  index: 1
  # Video capture settings
  fps: 8
  width: 256
  height: 256

capture:
  # Video duration in seconds (reduced from 2s to 1s for faster processing)
  duration: 1
  # Overlap in seconds (time between video starts)
  overlap: 0
  # Output format
  format: "mp4"
  # Temporary file prefix
  temp_prefix: "webcam_capture"
  # Number of frames to send for classification (reduced from 16 to 8)
  # Lower values = faster but potentially less accurate
  frames_per_clip: 8

logging:
  # Log file path
  file: "webcam/webcam_clf.log"
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  # Log format
  format: "%(asctime)s - %(levelname)s - %(message)s"

profiling:
  # Enable detailed performance profiling
  enabled: true
  # Show timing breakdown in each log line
  show_breakdown: true

optimizations:
  # Use in-memory buffer instead of temp files (faster, uses more RAM)
  use_memory_buffer: false
  # Use raw frames mode (bypasses video encoding/decoding - fastest!)
  # Requires /classify-frames endpoint support on server
  use_raw_frames: true
  # Use parallel processing (capture and inference in separate threads)
  # Achieves near-continuous processing by overlapping operations
  use_parallel_processing: true
